name: Web Release

on:
  release:
    types: [published]

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      attestations: write

    runs-on: ubuntu-latest

    name: Deploy release

    env:
      ARCHIVE_NAME: archive

    steps:
      - uses: actions/checkout@v4

      - name: Create archive
        run: tar -czf "$ARCHIVE_NAME".tar.gz out

      - name: Create checksum
        run: sha256sum "$ARCHIVE_NAME".tar.gz > ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: ${{ env.ARCHIVE_NAME }}.tar.gz

      - name: Upload archive as release asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz

      - name: Upload archive as release asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}-sha256-checksum.txt